In [1]:
import pandas as pd

In [41]:
df_xst=pd.read_csv('xstavka_names.csv')

In [47]:
df_xst.iloc[5:33]

,Unnamed: 0,Player 1,Player 2,1,X,2,O,Total,U,1*,...,2*,O*,IT1,U*,O*.1,IT2,U*.1,1*.1,2*.1,X*
5,0,Internazionale Milano,Getafe,1.77,3.42,5.4,1.18,1.35,2.12,1.784,...,2.08,2.41,-1+,1.595,1.73,1.5,2.1,1.73,0.5,2.1
6,1,Lautaro Martinez,Jaime Mata Arnaiz,3.52,1.712,5.7,1.168,2.21,1.33,1.9,...,1.94,1.608,0,2.384,3.64,0.5,1.29,3.64,0.5,1.29
7,2,Manchester United,LASK Linz,1.352,5.1,9.2,1.085,1.192,3.34,1.88,...,1.96,2.195,-1.5+,1.704,1.57,2,2.41,1.57,0.5,2.41
8,3,Cittadella,Frosinone Calcio,2.75,2.88,2.88,1.41,1.41,1.445,1.848,...,2,1.92,0,1.92,1.95,1,1.81,1.95,1,1.81
9,4,NK Istra 1961,Orijent,1.82,2.91,6.07,1.125,1.405,1.97,1.91,...,1.93,2.95,-1+,1.42,2.31,1,1.58,2.31,0.5,1.58
10,5,Al-Hussein,Al-Sareeh,1.34,4.03,13.1,1.01,1.225,3.1,1.7,...,2.15,2.27,-1+,1.64,2.56,1.5,1.48,2.56,0.5,1.48
11,6,Moghreb Tetouan,Raja Casablanca,3.48,2.98,2.24,1.61,1.37,1.285,2.256,...,1.64,2.37,0,1.59,2.04,0.5,1.74,2.04,1,1.74
12,7,Vojvodina Novi Sad,Cukaricki,2.17,3.21,3.36,1.3,1.325,1.65,2.08,...,1.75,1.57,0,2.41,2.04,1.5,1.75,2.04,1,1.75
13,8,Murici,Agremiacao Sportiva Arapiraquense,2.84,3.2,2.47,1.51,1.325,1.4,1.83,...,1.975,2.06,0,1.76,1.82,1,1.94,1.82,1,1.94
14,9,Concordia AC,Tubarao,1.03,15,29,-,-,9.98,2.24,...,1.65,2.37,-2.5+,1.59,2.21,2.5,1.64,2.21,0.5,1.64
15,10,Tombense,Associacao Atletica Caldense,2.41,3.01,3.11,1.344,1.365,1.536,1.97,...,1.832,1.66,0,2.22,1.75,1,2.03,1.75,0.5,2.03
16,11,Aguia de Maraba,Bragantino clube Do Para,15,8.08,1.14,5.27,1.06,-,2.256,...,1.64,2.21,+1.5-,1.67,2.22,0.5,1.63,2.22,2.5,1.63
17,12,Decisao,AAD Vitoria das Tabocas,5.7,3.72,1.6,2.26,1.256,1.125,1.81,...,2,1.78,+1-,2.03,1.69,0.5,2.12,1.69,1.5,2.12
18,13,Sport Club do Recife,Petrolina Social Futebol Clube,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
19,14,Crumlin United,Cherry Orchard,1.76,3.27,5.1,1.15,1.315,2.005,2.152,...,1.7,2.54,-1+,1.52,1.94,2,1.83,1.94,1.5,1.83
20,15,Bluebell United,Newbridge Town,1.15,7.47,15.1,-,1.075,5.02,2.08,...,1.75,2,-2+,1.81,2.38,2.5,1.55,2.38,0.5,1.55
21,16,Ballymun,Killester Donnycarney,4.57,3.3,1.83,1.925,1.31,1.18,2.152,...,1.7,1.52,+1-,2.54,1.59,0.5,2.29,1.59,1,2.29
22,17,Maynooth University Town,Malahide United,2.23,2.79,3.8,1.248,1.41,1.616,2.01,...,1.8,1.52,0,2.54,2.03,0.5,1.75,2.03,0.5,1.75
23,18,Portlaoise,Drumcondra,2.34,4.4,2.41,1.536,1.192,1.565,1.79,...,2.025,1.85,0,1.95,1.93,2,1.83,1.93,2,1.83
24,19,St. Mochta's,Wayside Celtic,1.33,5.4,7.56,1.07,1.136,3.165,2.152,...,1.7,2.07,-1.5+,1.76,1.88,2,1.88,1.88,0.5,1.88
25,20,Tolka Rovers,Collinstown,2.23,4.06,2.66,1.45,1.22,1.616,1.98,...,1.825,1.76,0,2.07,2.22,1.5,1.63,2.22,1.5,1.63
26,21,Greystones,Swords Celtic,1.83,4.59,3.26,1.315,1.18,1.92,1.83,...,1.975,2.31,-1+,1.61,1.59,1.5,2.29,1.59,1,2.29
27,22,Edenderry Town,Bangor GG,3.32,4.43,1.84,1.91,1.19,1.305,2.11,...,1.725,1.59,+1-,2.36,2.18,1.5,1.65,2.18,2,1.65
28,23,Liffey Wanderers,Portmarnock,1.52,4.98,4.72,1.17,1.155,2.435,1.925,...,1.875,1.78,-1+,2.04,2.22,2.5,1.63,2.22,1.5,1.63
29,24,Home Farm,Skerries Town,1.33,5.57,7.24,1.08,1.13,3.165,2.11,...,1.725,2.01,-1.5+,1.8,1.6,2.5,2.29,1.6,0.5,2.29
30,25,Alta U19,Bollstanas U19,1.28,5.84,8.56,1.056,1.12,3.488,1.84,...,1.96,1.85,-1.5+,1.95,1.97,5,1.8,1.97,3.5,1.8
31,26,Juventus+,Real+,8.69,7.97,1.19,4.16,1.048,1.035,1.9,...,1.9,1.944,+2-,1.856,1.71,2,2.14,1.71,4,2.14
32,27,Atletico (4х4),Paris Saint-Germain (4х4),2.235,5.35,2.235,1.575,1.12,1.575,1.915,...,1.885,1.9,0,1.9,1.77,3.5,2.05,1.77,3.5,2.05

In [60]:
df_xst.iloc[236:239]

,Unnamed: 0,Player 1,Player 2,1,X,2,O,Total,U,1*,...,2*,O*,IT1,U*,O*.1,IT2,U*.1,1*.1,2*.1,X*
236,0,Calgary Flames,Dallas Stars,5.06,4.35,1.6,2.344,1.22,1.17,2.096,...,1.77,-,+1-,-,1.85,1.5,1.95,-,-,-
237,1,Devils Team,Penguins Team,2.04,4.39,2.76,1.39,1.17,1.69,1.72,...,2.115,-,0,-,1.93,3,1.88,-,-,-
238,2,Severstal Team,Dinamo Team,2.395,6.25,1.984,1.73,1.085,1.504,1.945,...,1.856,-,0,-,1.91,3.5,1.89,-,-,-

In [62]:
df_xst.iloc[239:258].to_csv('xstavka_names39.csv')
#df_xstavka.to_csv('xstavka_names25.csv', mode='a', header=False)